# Generated by Django 3.2.5 on 2022-07-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='viewersmessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=1024)),
                ('email', models.CharField(default='NA', max_length=1024)),
                ('subject', models.CharField(default='NA', max_length=1024)),
                ('message', models.CharField(default='NA', max_length=5000)),
            ],
        ),
    ]
